using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "fae57fc4cf150a71")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Master</summary>
	[PublishedContentModel("master")]
	public partial class Master : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "master";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Master(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Master, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description (English)
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return this.GetPropertyValue<string>("metaDescription"); }
		}

		///<summary>
		/// Meta Description (Arabic)
		///</summary>
		[ImplementPropertyType("metaDescriptionArabic")]
		public string MetaDescriptionArabic
		{
			get { return this.GetPropertyValue<string>("metaDescriptionArabic"); }
		}

		///<summary>
		/// Meta Keywords (English)
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return this.GetPropertyValue<string>("metaKeywords"); }
		}

		///<summary>
		/// Meta Keywords (Arabic)
		///</summary>
		[ImplementPropertyType("metaKeywordsArabic")]
		public string MetaKeywordsArabic
		{
			get { return this.GetPropertyValue<string>("metaKeywordsArabic"); }
		}

		///<summary>
		/// Meta Title (English)
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return this.GetPropertyValue<string>("metaTitle"); }
		}

		///<summary>
		/// Meta Title (Arabic)
		///</summary>
		[ImplementPropertyType("metaTitleArabic")]
		public string MetaTitleArabic
		{
			get { return this.GetPropertyValue<string>("metaTitleArabic"); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Events</summary>
	[PublishedContentModel("Events")]
	public partial class Events : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Events";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Events(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Events, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Venue Owner</summary>
	[PublishedContentModel("VenuesOwner")]
	public partial class VenuesOwner : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "VenuesOwner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VenuesOwner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VenuesOwner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Info
		///</summary>
		[ImplementPropertyType("contactInfo")]
		public IEnumerable<IPublishedContent> ContactInfo
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("contactInfo"); }
		}

		///<summary>
		/// Description (English)
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Description (Arabic)
		///</summary>
		[ImplementPropertyType("descriptionArabic")]
		public IHtmlString DescriptionArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionArabic"); }
		}

		///<summary>
		/// Entity Website
		///</summary>
		[ImplementPropertyType("entityWebsite")]
		public string EntityWebsite
		{
			get { return this.GetPropertyValue<string>("entityWebsite"); }
		}

		///<summary>
		/// Name (Arabic)
		///</summary>
		[ImplementPropertyType("nameArabic")]
		public string NameArabic
		{
			get { return this.GetPropertyValue<string>("nameArabic"); }
		}

		///<summary>
		/// Name (English)
		///</summary>
		[ImplementPropertyType("ownerName")]
		public string OwnerName
		{
			get { return this.GetPropertyValue<string>("ownerName"); }
		}
	}

	/// <summary>Entities</summary>
	[PublishedContentModel("Entities")]
	public partial class Entities : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Entities";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Entities(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Entities, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Dashboard</summary>
	[PublishedContentModel("Dashboard")]
	public partial class Dashboard : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Dashboard";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Dashboard(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Dashboard, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Event</summary>
	[PublishedContentModel("Event")]
	public partial class Event : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Event";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Event(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Event, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Activities (English)
		///</summary>
		[ImplementPropertyType("activities")]
		public IEnumerable<string> Activities
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("activities"); }
		}

		///<summary>
		/// Activities (Arabic)
		///</summary>
		[ImplementPropertyType("activitiesArabic")]
		public IEnumerable<string> ActivitiesArabic
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("activitiesArabic"); }
		}

		///<summary>
		/// Amenities (English)
		///</summary>
		[ImplementPropertyType("amenities")]
		public IEnumerable<string> Amenities
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("amenities"); }
		}

		///<summary>
		/// Amenities (Arabic)
		///</summary>
		[ImplementPropertyType("amenitiesArabic")]
		public IEnumerable<string> AmenitiesArabic
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("amenitiesArabic"); }
		}

		///<summary>
		/// Audiences
		///</summary>
		[ImplementPropertyType("audiences")]
		public int Audiences
		{
			get { return this.GetPropertyValue<int>("audiences"); }
		}

		///<summary>
		/// Before you come (English)
		///</summary>
		[ImplementPropertyType("beforeYouCome")]
		public IEnumerable<string> BeforeYouCome
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("beforeYouCome"); }
		}

		///<summary>
		/// Before you come (Arabic)
		///</summary>
		[ImplementPropertyType("beforeYouComeArabic")]
		public IEnumerable<string> BeforeYouComeArabic
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("beforeYouComeArabic"); }
		}

		///<summary>
		/// Event Contents (English)
		///</summary>
		[ImplementPropertyType("eventContents")]
		public IHtmlString EventContents
		{
			get { return this.GetPropertyValue<IHtmlString>("eventContents"); }
		}

		///<summary>
		/// Event Contents (Arabic)
		///</summary>
		[ImplementPropertyType("eventContentsArabic")]
		public IHtmlString EventContentsArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("eventContentsArabic"); }
		}

		///<summary>
		/// Event Name (English)
		///</summary>
		[ImplementPropertyType("eventName")]
		public string EventName
		{
			get { return this.GetPropertyValue<string>("eventName"); }
		}

		///<summary>
		/// Event Name (Arabic)
		///</summary>
		[ImplementPropertyType("eventNameArabic")]
		public string EventNameArabic
		{
			get { return this.GetPropertyValue<string>("eventNameArabic"); }
		}

		///<summary>
		/// Event Occurance
		///</summary>
		[ImplementPropertyType("eventOccurance")]
		public IEnumerable<IPublishedContent> EventOccurance
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("eventOccurance"); }
		}

		///<summary>
		/// Event Organizer
		///</summary>
		[ImplementPropertyType("eventOrganizer")]
		public IEnumerable<IPublishedContent> EventOrganizer
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("eventOrganizer"); }
		}

		///<summary>
		/// Event Status
		///</summary>
		[ImplementPropertyType("eventStatus")]
		public int EventStatus
		{
			get { return this.GetPropertyValue<int>("eventStatus"); }
		}

		///<summary>
		/// Event Tags
		///</summary>
		[ImplementPropertyType("eventTags")]
		public IEnumerable<string> EventTags
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("eventTags"); }
		}

		///<summary>
		/// Event Thumbnail
		///</summary>
		[ImplementPropertyType("eventThumbnail")]
		public string EventThumbnail
		{
			get { return this.GetPropertyValue<string>("eventThumbnail"); }
		}

		///<summary>
		/// Event Video (English)
		///</summary>
		[ImplementPropertyType("eventVideo")]
		public IPublishedContent EventVideo
		{
			get { return this.GetPropertyValue<IPublishedContent>("eventVideo"); }
		}

		///<summary>
		/// Event Video (Arabic)
		///</summary>
		[ImplementPropertyType("eventVideoArabic")]
		public IPublishedContent EventVideoArabic
		{
			get { return this.GetPropertyValue<IPublishedContent>("eventVideoArabic"); }
		}

		///<summary>
		/// Event Website
		///</summary>
		[ImplementPropertyType("eventWebsite")]
		public string EventWebsite
		{
			get { return this.GetPropertyValue<string>("eventWebsite"); }
		}

		///<summary>
		/// Offer Description (English)
		///</summary>
		[ImplementPropertyType("offerDescription")]
		public IHtmlString OfferDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("offerDescription"); }
		}

		///<summary>
		/// Offer Description (Arabic)
		///</summary>
		[ImplementPropertyType("offerDescriptionArabic")]
		public IHtmlString OfferDescriptionArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("offerDescriptionArabic"); }
		}

		///<summary>
		/// Name (English): mandatory if Promotion Logo has picked
		///</summary>
		[ImplementPropertyType("pName")]
		public string PName
		{
			get { return this.GetPropertyValue<string>("pName"); }
		}

		///<summary>
		/// Name (Arabic): mandatory if Promotion Logo has picked
		///</summary>
		[ImplementPropertyType("pNameArabic")]
		public string PNameArabic
		{
			get { return this.GetPropertyValue<string>("pNameArabic"); }
		}

		///<summary>
		/// Promotion Duration
		///</summary>
		[ImplementPropertyType("promotionDuration")]
		public Diplo.DateRangePicker.DateRange PromotionDuration
		{
			get { return this.GetPropertyValue<Diplo.DateRangePicker.DateRange>("promotionDuration"); }
		}

		///<summary>
		/// Promotion Logo
		///</summary>
		[ImplementPropertyType("promotionLogo")]
		public string PromotionLogo
		{
			get { return this.GetPropertyValue<string>("promotionLogo"); }
		}

		///<summary>
		/// Retrieve from Twitter
		///</summary>
		[ImplementPropertyType("retrieveFromTwitter")]
		public object RetrieveFromTwitter
		{
			get { return this.GetPropertyValue("retrieveFromTwitter"); }
		}

		///<summary>
		/// Tickets
		///</summary>
		[ImplementPropertyType("tickets")]
		public object Tickets
		{
			get { return this.GetPropertyValue("tickets"); }
		}

		///<summary>
		/// Upload Image component (English)
		///</summary>
		[ImplementPropertyType("uploadImageComponent")]
		public IEnumerable<IPublishedContent> UploadImageComponent
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uploadImageComponent"); }
		}

		///<summary>
		/// Upload Image component (Arabic)
		///</summary>
		[ImplementPropertyType("uploadImageComponentArabic")]
		public IEnumerable<IPublishedContent> UploadImageComponentArabic
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uploadImageComponentArabic"); }
		}
	}

	/// <summary>Nested DataTypes</summary>
	[PublishedContentModel("NestedDataTypes")]
	public partial class NestedDataTypes : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "NestedDataTypes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NestedDataTypes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NestedDataTypes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Settings</summary>
	[PublishedContentModel("settings")]
	public partial class Settings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Settings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Settings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Cities</summary>
	[PublishedContentModel("cities")]
	public partial class Cities : Settings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cities";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Cities(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Cities, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>City</summary>
	[PublishedContentModel("city")]
	public partial class City : Settings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "city";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public City(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<City, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Name (Arabic)
		///</summary>
		[ImplementPropertyType("nameArabic")]
		public string NameArabic
		{
			get { return this.GetPropertyValue<string>("nameArabic"); }
		}

		///<summary>
		/// Name (English)
		///</summary>
		[ImplementPropertyType("nameEnglish")]
		public string NameEnglish
		{
			get { return this.GetPropertyValue<string>("nameEnglish"); }
		}
	}

	/// <summary>Venue</summary>
	[PublishedContentModel("Venue")]
	public partial class Venue : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Venue";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Venue(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Venue, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Floor Map (English)
		///</summary>
		[ImplementPropertyType("floorMap")]
		public IEnumerable<IPublishedContent> FloorMap
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("floorMap"); }
		}

		///<summary>
		/// Floor Map (Arabic)
		///</summary>
		[ImplementPropertyType("floorMapArabic")]
		public IPublishedContent FloorMapArabic
		{
			get { return this.GetPropertyValue<IPublishedContent>("floorMapArabic"); }
		}

		///<summary>
		/// Tags (English)
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<string> Tags
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("tags"); }
		}

		///<summary>
		/// Tags (Arabic)
		///</summary>
		[ImplementPropertyType("tagsArabic")]
		public IEnumerable<string> TagsArabic
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("tagsArabic"); }
		}

		///<summary>
		/// Venue City
		///</summary>
		[ImplementPropertyType("venueCity")]
		public object VenueCity
		{
			get { return this.GetPropertyValue("venueCity"); }
		}

		///<summary>
		/// Venue Contact Number
		///</summary>
		[ImplementPropertyType("venueContactNumber")]
		public string VenueContactNumber
		{
			get { return this.GetPropertyValue<string>("venueContactNumber"); }
		}

		///<summary>
		/// Venue Description (English)
		///</summary>
		[ImplementPropertyType("venueDescription")]
		public IHtmlString VenueDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("venueDescription"); }
		}

		///<summary>
		/// Venue Description (Arabic)
		///</summary>
		[ImplementPropertyType("venueDescriptionArabic")]
		public IHtmlString VenueDescriptionArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("venueDescriptionArabic"); }
		}

		///<summary>
		/// Venue Location
		///</summary>
		[ImplementPropertyType("venueLocation")]
		public object VenueLocation
		{
			get { return this.GetPropertyValue("venueLocation"); }
		}

		///<summary>
		/// Venue Name (English)
		///</summary>
		[ImplementPropertyType("venueName")]
		public string VenueName
		{
			get { return this.GetPropertyValue<string>("venueName"); }
		}

		///<summary>
		/// Venue Name (Arabic)
		///</summary>
		[ImplementPropertyType("venueNameArabic")]
		public string VenueNameArabic
		{
			get { return this.GetPropertyValue<string>("venueNameArabic"); }
		}

		///<summary>
		/// Opening Time
		///</summary>
		[ImplementPropertyType("venueOpeningTime")]
		public object VenueOpeningTime
		{
			get { return this.GetPropertyValue("venueOpeningTime"); }
		}

		///<summary>
		/// Venue Owner
		///</summary>
		[ImplementPropertyType("venueOwner")]
		public IEnumerable<IPublishedContent> VenueOwner
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("venueOwner"); }
		}

		///<summary>
		/// Venue Representative (English)
		///</summary>
		[ImplementPropertyType("venueRepresentative")]
		public string VenueRepresentative
		{
			get { return this.GetPropertyValue<string>("venueRepresentative"); }
		}

		///<summary>
		/// Venue Representative (Arabic)
		///</summary>
		[ImplementPropertyType("venueRepresentativeArabic")]
		public string VenueRepresentativeArabic
		{
			get { return this.GetPropertyValue<string>("venueRepresentativeArabic"); }
		}

		///<summary>
		/// Special Occasions
		///</summary>
		[ImplementPropertyType("venueSpecialOccasion")]
		public IEnumerable<IPublishedContent> VenueSpecialOccasion
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("venueSpecialOccasion"); }
		}
	}

	/// <summary>Shops</summary>
	[PublishedContentModel("Shops")]
	public partial class Shops : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Shops";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shops(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shops, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Standard RTE</summary>
	[PublishedContentModel("standardRTE")]
	public partial class StandardRte : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "standardRTE";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StandardRte(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StandardRte, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Page Banner (English)
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public IPublishedContent PageBanner
		{
			get { return this.GetPropertyValue<IPublishedContent>("pageBanner"); }
		}

		///<summary>
		/// Page Banner (Arabic)
		///</summary>
		[ImplementPropertyType("pageBannerArabic")]
		public IPublishedContent PageBannerArabic
		{
			get { return this.GetPropertyValue<IPublishedContent>("pageBannerArabic"); }
		}

		///<summary>
		/// Page Contents (English)
		///</summary>
		[ImplementPropertyType("pageContents")]
		public IHtmlString PageContents
		{
			get { return this.GetPropertyValue<IHtmlString>("pageContents"); }
		}

		///<summary>
		/// Page Contents (Arabic)
		///</summary>
		[ImplementPropertyType("pageContentsArabic")]
		public IHtmlString PageContentsArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("pageContentsArabic"); }
		}

		///<summary>
		/// Page Title (English)
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// Page Title (Arabic)
		///</summary>
		[ImplementPropertyType("pageTitleArabic")]
		public string PageTitleArabic
		{
			get { return this.GetPropertyValue<string>("pageTitleArabic"); }
		}
	}

	/// <summary>Themes</summary>
	[PublishedContentModel("Themes")]
	public partial class Themes : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Themes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Themes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Themes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Theme</summary>
	[PublishedContentModel("Theme")]
	public partial class Theme : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Theme";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Theme(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Theme, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Page Banner (English)
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public IPublishedContent PageBanner
		{
			get { return this.GetPropertyValue<IPublishedContent>("pageBanner"); }
		}

		///<summary>
		/// Page Banner (Arabic)
		///</summary>
		[ImplementPropertyType("pageBannerArabic")]
		public string PageBannerArabic
		{
			get { return this.GetPropertyValue<string>("pageBannerArabic"); }
		}

		///<summary>
		/// Page Contents (English)
		///</summary>
		[ImplementPropertyType("pageContents")]
		public IHtmlString PageContents
		{
			get { return this.GetPropertyValue<IHtmlString>("pageContents"); }
		}

		///<summary>
		/// Page Contents (Arabic)
		///</summary>
		[ImplementPropertyType("pageContentsArabic")]
		public IHtmlString PageContentsArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("pageContentsArabic"); }
		}

		///<summary>
		/// Page Events
		///</summary>
		[ImplementPropertyType("pageEvents")]
		public IEnumerable<IPublishedContent> PageEvents
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("pageEvents"); }
		}

		///<summary>
		/// Upload Brochure (English)
		///</summary>
		[ImplementPropertyType("uploadBrochure")]
		public IPublishedContent UploadBrochure
		{
			get { return this.GetPropertyValue<IPublishedContent>("uploadBrochure"); }
		}

		///<summary>
		/// Upload Brochure (Arabic)
		///</summary>
		[ImplementPropertyType("uploadBrochureArabic")]
		public IPublishedContent UploadBrochureArabic
		{
			get { return this.GetPropertyValue<IPublishedContent>("uploadBrochureArabic"); }
		}
	}

	/// <summary>Questions</summary>
	[PublishedContentModel("Questions")]
	public partial class Questions : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Questions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Questions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Questions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Question</summary>
	[PublishedContentModel("Question")]
	public partial class Question : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Question";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Question(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Question, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Question Title (English)
		///</summary>
		[ImplementPropertyType("questionTitle")]
		public string QuestionTitle
		{
			get { return this.GetPropertyValue<string>("questionTitle"); }
		}

		///<summary>
		/// Question Title (Arabic)
		///</summary>
		[ImplementPropertyType("questionTitleArabic")]
		public string QuestionTitleArabic
		{
			get { return this.GetPropertyValue<string>("questionTitleArabic"); }
		}
	}

	/// <summary>QuestionsList</summary>
	[PublishedContentModel("QuestionList")]
	public partial class QuestionList : NestedDataTypes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "QuestionList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuestionList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuestionList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Question Title (English)
		///</summary>
		[ImplementPropertyType("questionTitle")]
		public string QuestionTitle
		{
			get { return this.GetPropertyValue<string>("questionTitle"); }
		}

		///<summary>
		/// Question Title (Arabic)
		///</summary>
		[ImplementPropertyType("questionTitleArabic")]
		public string QuestionTitleArabic
		{
			get { return this.GetPropertyValue<string>("questionTitleArabic"); }
		}
	}

	/// <summary>Government Entities</summary>
	[PublishedContentModel("GovernmentEntities")]
	public partial class GovernmentEntities : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "GovernmentEntities";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GovernmentEntities(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GovernmentEntities, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Event Organizers</summary>
	[PublishedContentModel("EventOrganizers")]
	public partial class EventOrganizers : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "EventOrganizers";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EventOrganizers(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EventOrganizers, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Venue Owners</summary>
	[PublishedContentModel("VenueOwners")]
	public partial class VenueOwners : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "VenueOwners";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VenueOwners(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VenueOwners, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Entity</summary>
	[PublishedContentModel("GovernmentEntity")]
	public partial class GovernmentEntity : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "GovernmentEntity";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GovernmentEntity(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GovernmentEntity, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description (English)
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Description (Arabic)
		///</summary>
		[ImplementPropertyType("descriptionArabic")]
		public IHtmlString DescriptionArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionArabic"); }
		}

		///<summary>
		/// Name (English)
		///</summary>
		[ImplementPropertyType("entityName")]
		public string EntityName
		{
			get { return this.GetPropertyValue<string>("entityName"); }
		}

		///<summary>
		/// Name (Arabic)
		///</summary>
		[ImplementPropertyType("entityNameArabic")]
		public string EntityNameArabic
		{
			get { return this.GetPropertyValue<string>("entityNameArabic"); }
		}

		///<summary>
		/// Entity Website
		///</summary>
		[ImplementPropertyType("entityWebsite")]
		public string EntityWebsite
		{
			get { return this.GetPropertyValue<string>("entityWebsite"); }
		}

		///<summary>
		/// Related Venues
		///</summary>
		[ImplementPropertyType("relatedVenues")]
		public IEnumerable<IPublishedContent> RelatedVenues
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("relatedVenues"); }
		}
	}

	/// <summary>Organizer</summary>
	[PublishedContentModel("Organizer")]
	public partial class Organizer : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Organizer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Organizer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Organizer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Info
		///</summary>
		[ImplementPropertyType("contactInfo")]
		public IEnumerable<IPublishedContent> ContactInfo
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("contactInfo"); }
		}

		///<summary>
		/// Description (English)
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Description (Arabic)
		///</summary>
		[ImplementPropertyType("descriptionArabic")]
		public IHtmlString DescriptionArabic
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionArabic"); }
		}

		///<summary>
		/// Entity Website
		///</summary>
		[ImplementPropertyType("entityWebsite")]
		public string EntityWebsite
		{
			get { return this.GetPropertyValue<string>("entityWebsite"); }
		}

		///<summary>
		/// Name (English)
		///</summary>
		[ImplementPropertyType("organizerName")]
		public string OrganizerName
		{
			get { return this.GetPropertyValue<string>("organizerName"); }
		}

		///<summary>
		/// Name (Arabic)
		///</summary>
		[ImplementPropertyType("organizerNameArabic")]
		public string OrganizerNameArabic
		{
			get { return this.GetPropertyValue<string>("organizerNameArabic"); }
		}
	}

	/// <summary>Contact Info</summary>
	[PublishedContentModel("contactInfo")]
	public partial class ContactInfo : NestedDataTypes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactInfo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactInfo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactInfo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Landline
		///</summary>
		[ImplementPropertyType("landline")]
		public string Landline
		{
			get { return this.GetPropertyValue<string>("landline"); }
		}

		///<summary>
		/// Mobile Number
		///</summary>
		[ImplementPropertyType("mobileNumber")]
		public string MobileNumber
		{
			get { return this.GetPropertyValue<string>("mobileNumber"); }
		}
	}

	/// <summary>Special Occasions</summary>
	[PublishedContentModel("specialOccasions")]
	public partial class SpecialOccasions : NestedDataTypes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "specialOccasions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SpecialOccasions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SpecialOccasions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Special Occasion
		///</summary>
		[ImplementPropertyType("specialOccasion")]
		public object SpecialOccasion
		{
			get { return this.GetPropertyValue("specialOccasion"); }
		}
	}

	/// <summary>Event Occurances</summary>
	[PublishedContentModel("eventOccurances")]
	public partial class EventOccurances : NestedDataTypes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "eventOccurances";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EventOccurances(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EventOccurances, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// EventOccurance
		///</summary>
		[ImplementPropertyType("eventOccurance")]
		public object EventOccurance
		{
			get { return this.GetPropertyValue("eventOccurance"); }
		}
	}

	/// <summary>Shop</summary>
	[PublishedContentModel("Shop")]
	public partial class Shop : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Shop";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shop(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shop, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("logo"); }
		}

		///<summary>
		/// Shop Location (English)
		///</summary>
		[ImplementPropertyType("shopLocation")]
		public string ShopLocation
		{
			get { return this.GetPropertyValue<string>("shopLocation"); }
		}

		///<summary>
		/// Shop Location (Arabic)
		///</summary>
		[ImplementPropertyType("shopLocationArabic")]
		public string ShopLocationArabic
		{
			get { return this.GetPropertyValue<string>("shopLocationArabic"); }
		}

		///<summary>
		/// Name (English)
		///</summary>
		[ImplementPropertyType("shopName")]
		public string ShopName
		{
			get { return this.GetPropertyValue<string>("shopName"); }
		}

		///<summary>
		/// Name (Arabic)
		///</summary>
		[ImplementPropertyType("shopNameArabic")]
		public string ShopNameArabic
		{
			get { return this.GetPropertyValue<string>("shopNameArabic"); }
		}
	}

	/// <summary>Venues</summary>
	[PublishedContentModel("Venues")]
	public partial class Venues : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Venues";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Venues(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Venues, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>About</summary>
	[PublishedContentModel("About")]
	public partial class About : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "About";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public About(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<About, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>SignIn</summary>
	[PublishedContentModel("SignIn")]
	public partial class SignIn : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SignIn";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SignIn(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SignIn, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>SignUp</summary>
	[PublishedContentModel("SignUp")]
	public partial class SignUp : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SignUp";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SignUp(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SignUp, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
